Re-worked much of the temporary file handling patch to make it actually do at least some of what it was supposed to; also patched the fail-open use in configure.
vasprintf() just can't be used like that, it returns an int and not the
string.  And this chunk wasn't required anyway.

"trap" can only be used once per signal.

Use "rm -f" on non-directories, not "rm -rf".

In cvsbug, use the $xs variable for exit code as the rest of the script
relies upon it.

This is still mostly untested (although I'm doing the commit with the new
package already).  Whoever reads this, -- please find the time and test
everything that's touched by the patch! ;-)

CVS-ID: packages/cvs/cvs-1.11.5-alt-owl-tmp.diff 1.2
CVS-ID: packages/cvs/cvs.spec 1.2

diff --git a/packages/cvs/cvs-1.11.5-alt-owl-tmp.diff b/packages/cvs/cvs-1.11.5-alt-owl-tmp.diff
--- a/packages/cvs/cvs-1.11.5-alt-owl-tmp.diff
+++ b/packages/cvs/cvs-1.11.5-alt-owl-tmp.diff
@@ -1,38 +1,68 @@
+diff -ur cvs-1.11.5.orig/configure cvs-1.11.5/configure
+--- cvs-1.11.5.orig/configure	Thu Jan 16 21:36:48 2003
++++ cvs-1.11.5/configure	Sun Apr 27 13:31:05 2003
+@@ -10184,24 +10184,13 @@
+ # Create a temporary directory, and hook for its removal unless debugging.
+ $debug ||
+ {
+-  trap 'exit_status=$?; rm -rf $tmp && exit $exit_status' 0
+-  trap '{ (exit 1); exit 1; }' 1 2 13 15
++  tmp=
++  trap 'exit_status=$?; rm -rf -- "$tmp"; exit $exit_status' EXIT
++  trap 'trap - EXIT; rm -rf -- "$tmp"; exit 1' HUP INT PIPE TERM
+ }
+ 
+ # Create a (secure) tmp directory for tmp files.
+-: ${TMPDIR=/tmp}
+-{
+-  tmp=`(umask 077 && mktemp -d -q "$TMPDIR/csXXXXXX") 2>/dev/null` &&
+-  test -n "$tmp" && test -d "$tmp"
+-}  ||
+-{
+-  tmp=$TMPDIR/cs$$-$RANDOM
+-  (umask 077 && mkdir $tmp)
+-} ||
+-{
+-   echo "$me: cannot create a temporary directory in $TMPDIR" >&2
+-   { (exit 1); exit 1; }
+-}
++tmp="`mktemp -dt cs.XXXXXXXXXX`" || exit 1
+ 
+ _ACEOF
+ 
 diff -ur cvs-1.11.5.orig/contrib/cvs2vendor.sh cvs-1.11.5/contrib/cvs2vendor.sh
 --- cvs-1.11.5.orig/contrib/cvs2vendor.sh	Wed Feb 12 15:34:55 1997
-+++ cvs-1.11.5/contrib/cvs2vendor.sh	Tue Apr 22 14:51:04 2003
-@@ -36,11 +36,15 @@
++++ cvs-1.11.5/contrib/cvs2vendor.sh	Sun Apr 27 12:49:20 2003
+@@ -36,11 +36,12 @@
  tsrcdir=$1
  tdstdir=$2
  
 -revfile=/tmp/cvs2vendor_$$_rev
 -rm -f $revfile
-+revfile=
-+trap 'rm -rf -- "$revfile"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$revfile"; exit 1' HUP INT QUIT TERM
-+revfile=`/bin/mktemp -t cvs2vendor_rev.XXXXXXXXXX` || exit
- 
+-
 -commentfile=/tmp/cvs2vendor_$$_comment
 -rm -f $commentfile
++revfile=
 +commentfile=
-+trap 'rm -rf -- "$commentfile"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$commentfile"; exit 1' HUP INT QUIT TERM
-+commentfile=`/bin/mktemp -t cvs2vendor_comment.XXXXXXXXXX` || exit
++trap 'rm -f -- "$revfile" "$commentfile"' EXIT
++trap 'trap - EXIT ; rm -f -- "$revfile" "$commentfile"; exit 1' HUP INT QUIT TERM
++revfile="`mktemp -t cvs2vendor_rev.XXXXXXXXXX`" || exit
++commentfile="`mktemp -t cvs2vendor_comment.XXXXXXXXXX`" || exit
  
  srcdirs=`cd $tsrcdir && find . -type d -print | sed 's~^\.[/]*~~'`
  
 diff -ur cvs-1.11.5.orig/contrib/debug_check_log.sh cvs-1.11.5/contrib/debug_check_log.sh
 --- cvs-1.11.5.orig/contrib/debug_check_log.sh	Fri Nov  8 17:27:40 2002
-+++ cvs-1.11.5/contrib/debug_check_log.sh	Tue Apr 22 14:32:09 2003
++++ cvs-1.11.5/contrib/debug_check_log.sh	Sun Apr 27 12:34:36 2003
 @@ -19,7 +19,10 @@
  # Contributed by Derek R. Price <derek.price@openavenue.com>
  #
  
 -
 +dcldir=
-+trap 'rm -rf -- $dcldir"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$dcldir" ; exit 1' HUP INT QUIT TERM
-+dcldir=`mktemp -td dcl.XXXXXXXXXX` || exit
++trap 'rm -rf -- "$dcldir"' EXIT
++trap 'trap - EXIT; rm -rf -- "$dcldir"; exit 1' HUP INT QUIT TERM
++dcldir="`mktemp -td dcl.XXXXXXXXXX`" || exit
  
  usage ()
  {
@@ -106,22 +136,22 @@ diff -ur cvs-1.11.5.orig/contrib/debug_check_log.sh cvs-1.11.5/contrib/debug_che
  ###
 diff -ur cvs-1.11.5.orig/contrib/rcs-to-cvs.sh cvs-1.11.5/contrib/rcs-to-cvs.sh
 --- cvs-1.11.5.orig/contrib/rcs-to-cvs.sh	Fri Feb 21 03:44:46 1997
-+++ cvs-1.11.5/contrib/rcs-to-cvs.sh	Tue Apr 22 14:52:28 2003
++++ cvs-1.11.5/contrib/rcs-to-cvs.sh	Sun Apr 27 12:36:26 2003
 @@ -32,7 +32,10 @@
  usage="Usage: rcs-to-cvs [-v] [-m message] [-f message_file] repository"
  vbose=0
  message=""
 -if [ -d /var/tmp ]; then message_file=/var/tmp/checkin.$$; else message_file=/usr/tmp/checkin.$$; fi
 +message_file=
-+trap 'rm -rf -- "$message_file"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$message_file"; exit 1' HUP INT QUIT TERM
-+message_file=`/bin/mktemp -t checkin.XXXXXXXXXX` || exit
++trap 'rm -f -- "$message_file"' EXIT
++trap 'trap - EXIT; rm -f -- "$message_file"; exit 1' HUP INT QUIT TERM
++message_file="`mktemp -t checkin.XXXXXXXXXX`" || exit
  got_one=0
  
  if [ $# -lt 1 ]; then
 diff -ur cvs-1.11.5.orig/contrib/rcs2log.sh cvs-1.11.5/contrib/rcs2log.sh
 --- cvs-1.11.5.orig/contrib/rcs2log.sh	Thu Sep  6 15:55:51 2001
-+++ cvs-1.11.5/contrib/rcs2log.sh	Sun Apr 27 12:08:20 2003
++++ cvs-1.11.5/contrib/rcs2log.sh	Sun Apr 27 12:37:20 2003
 @@ -182,10 +182,12 @@
  	m[9]="Oct"; m[10]="Nov"; m[11]="Dec"
  '
@@ -129,8 +159,8 @@ diff -ur cvs-1.11.5.orig/contrib/rcs2log.sh cvs-1.11.5/contrib/rcs2log.sh
 -logdir=$TMPDIR/rcs2log$$
 +logdir=
 +trap 'rm -rf -- "$logdir"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$logdir"; exit 1' HUP INT QUIT TERM
-+logdir=`/bin/mktemp -td rcs2log.XXXXXXXXXX` || exit
++trap 'trap - EXIT; rm -rf -- "$logdir"; exit 1' HUP INT QUIT TERM
++logdir="`mktemp -td rcs2log.XXXXXXXXXX`" || exit
 +
  llogout=$logdir/l
 -trap exit 1 2 13 15
@@ -140,7 +170,7 @@ diff -ur cvs-1.11.5.orig/contrib/rcs2log.sh cvs-1.11.5/contrib/rcs2log.sh
  # If no rlog-format log file is given, generate one into $rlogfile.
 diff -ur cvs-1.11.5.orig/contrib/rcs2sccs.sh cvs-1.11.5/contrib/rcs2sccs.sh
 --- cvs-1.11.5.orig/contrib/rcs2sccs.sh	Tue Oct 16 19:06:24 2001
-+++ cvs-1.11.5/contrib/rcs2sccs.sh	Sun Apr 27 12:08:20 2003
++++ cvs-1.11.5/contrib/rcs2sccs.sh	Sun Apr 27 12:38:59 2003
 @@ -9,20 +9,19 @@
      mkdir SCCS
  fi
@@ -154,12 +184,12 @@ diff -ur cvs-1.11.5.orig/contrib/rcs2sccs.sh cvs-1.11.5/contrib/rcs2sccs.sh
 -initialfile=/tmp/rcs2sccs_$$_init
 +rcs2sccsdir=
 +trap 'rm -rf -- "$rcs2sccsdir"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$rcs2sccsdir"; exit 1' HUP INT QUIT TERM
-+rcs2sccsdir=`/bin/mktemp -td rcs2sccs.XXXXXXXXXX` || exit
++trap 'trap - EXIT; rm -rf -- "$rcs2sccsdir"; exit 1' HUP INT QUIT TERM
++rcs2sccsdir="`mktemp -td rcs2sccs.XXXXXXXXXX`" || exit
 +logfile="$rcs2sccsdir/log"
 +tmpfile="$rcs2sccsdir/tmp"
 +emptyfile="$rcs2sccsdir/empty"
-+:>$emptyfile
++> $emptyfile
 +initialfile="$rcs2sccsdir/init"
  echo "Initial revision" > $initialfile
 -sedfile=/tmp/rcs2sccs_$$_sed
@@ -195,36 +225,46 @@ diff -ur cvs-1.11.5.orig/man/cvsbug.8 cvs-1.11.5/man/cvsbug.8
  .B INSTALL
 diff -ur cvs-1.11.5.orig/src/cvsbug.in cvs-1.11.5/src/cvsbug.in
 --- cvs-1.11.5.orig/src/cvsbug.in	Mon Apr 29 04:45:47 2002
-+++ cvs-1.11.5/src/cvsbug.in	Sun Apr 27 12:08:20 2003
-@@ -83,11 +83,20 @@
++++ cvs-1.11.5/src/cvsbug.in	Sun Apr 27 12:48:05 2003
+@@ -83,11 +83,18 @@
  
  #
  
 -[ -z "$TMPDIR" ] && TMPDIR=/tmp
-+[ -n "$TMPDIR" ] || TMPDIR=/tmp
++# $xs kludge apparently needed by Sun /bin/sh (and is relied upon by the
++# rest of this script, on all platforms).
++xs=0
  
 -TEMP=$TMPDIR/p$$
 -BAD=$TMPDIR/pbad$$
 -REF=$TMPDIR/pf$$
 +TEMP=
-+trap 'rm -rf -- "$TEMP"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$TEMP"; exit 1' HUP INT QUIT TERM
-+TEMP="`/bin/mktemp -t p.XXXXXXXXXX`"
 +BAD=
-+trap 'rm -rf -- "$BAD"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$BAD"; exit 1' HUP INT QUIT TERM
-+BAD="`/bin/mktemp -t pbad.XXXXXXXXXX`"
 +REF=
-+trap 'rm -rf -- "$REF"' EXIT
-+trap 'trap - EXIT ; rm -rf -- "$REF"; exit 1' HUP INT QUIT TERM
-+REF="`/bin/mktemp -t pf.XXXXXXXXXX`"
++trap 'rm -f -- "$TEMP" "$BAD" "$REF"; exit $xs' EXIT
++trap 'trap - EXIT; rm -f -- "$TEMP" "$BAD" "$REF"; exit 1' HUP INT QUIT TERM
++TEMP="`mktemp -t p.XXXXXXXXXX`"
++BAD="`mktemp -t pbad.XXXXXXXXXX`"
++REF="`mktemp -t pf.XXXXXXXXXX`"
  
  if [ -z "$LOGNAME" -a -n "$USER" ]; then
    LOGNAME=$USER
+@@ -263,11 +270,6 @@
+ DESCRIPTION_C='<precise description of the problem (multiple lines)>'
+ HOW_TO_REPEAT_C='<code/input/activities to reproduce the problem (multiple lines)>'
+ FIX_C='<how to correct or work around the problem, if known (multiple lines)>'
+-
+-# Catch some signals. ($xs kludge needed by Sun /bin/sh)
+-xs=0
+-trap 'rm -f $REF $TEMP; exit $xs' 0
+-trap 'echo "$COMMAND: Aborting ..."; rm -f $REF $TEMP; xs=1; exit' 1 2 3 13 15
+ 
+ # If they told us to use a specific file, then do so.
+ if [ -n "$IN_FILE" ]; then
 diff -ur cvs-1.11.5.orig/src/filesubr.c cvs-1.11.5/src/filesubr.c
 --- cvs-1.11.5.orig/src/filesubr.c	Tue Sep 24 20:47:09 2002
-+++ cvs-1.11.5/src/filesubr.c	Sun Apr 27 12:08:20 2003
-@@ -703,10 +703,18 @@
++++ cvs-1.11.5/src/filesubr.c	Sun Apr 27 13:10:43 2003
+@@ -703,7 +703,7 @@
      if (fp == NULL)
  	error (1, errno, "Failed to create temporary file");
      if (fclose (fp) == EOF)
@@ -233,39 +273,46 @@ diff -ur cvs-1.11.5.orig/src/filesubr.c cvs-1.11.5/src/filesubr.c
      return fn;
  }
  
-+FILE *cvs_xtemp_file (char **filename)
-+{
-+    FILE *fp = cvs_temp_file (filename);
-+    if (fp == NULL)
-+	error (1, errno, "Failed to create temporary file: %s", *filename);
-+    return fp;
-+}
-+
- /* Generate a unique temporary filename and return an open file stream
-  * to the truncated file by that name
-  *
-@@ -754,11 +762,7 @@
- #ifdef HAVE_MKSTEMP
+@@ -755,9 +755,10 @@
  
      {
--    int fd;
--
+     int fd;
++    int save_errno;
+ 
 -    fn = xmalloc (strlen (Tmpdir) + 11);
 -    sprintf (fn, "%s/%s", Tmpdir, "cvsXXXXXX" );
--    fd = mkstemp (fn);
-+    int fd = mkstemp (vasprintf (&fn, "%s/%s", Tmpdir, "cvs.XXXXXX"));
++    fn = xmalloc (strlen (Tmpdir) + 12);
++    sprintf (fn, "%s/%s", Tmpdir, "cvs.XXXXXX" );
+     fd = mkstemp (fn);
  
      /* a NULL return will be interpreted by callers as an error and
-      * errno should still be set
-@@ -778,11 +782,6 @@
+@@ -766,23 +767,25 @@
+     if (fd == -1) fp = NULL;
+     else if ((fp = CVS_FDOPEN (fd, "w+")) == NULL)
+     {
+-	/* attempt to close and unlink the file since mkstemp returned sucessfully and
++	/* attempt to unlink the file since mkstemp returned sucessfully and
+ 	 * we believe it's been created and opened
+ 	 */
+- 	int save_errno = errno;
++	save_errno = errno;
+ 	if (close (fd))
+-	    error (0, errno, "Failed to close temporary file %s", fn);
++	    error (1, errno, "Failed to close temporary file %s", fn);
+ 	if (CVS_UNLINK (fn))
+-	    error (0, errno, "Failed to unlink temporary file %s", fn);
++	    error (1, errno, "Failed to unlink temporary file %s", fn);
+ 	errno = save_errno;
      }
  
++    save_errno = errno;
      if (fp == NULL) free (fn);
--    /* mkstemp is defined to open mode 0600 using glibc 2.0.7+ */
--    /* FIXME - configure can probably tell us which version of glibc we are
--     * linking to and not chmod for 2.0.7+
--     */
--    else chmod (fn, 0600);
+     /* mkstemp is defined to open mode 0600 using glibc 2.0.7+ */
+     /* FIXME - configure can probably tell us which version of glibc we are
+      * linking to and not chmod for 2.0.7+
+      */
+     else chmod (fn, 0600);
++    errno = save_errno;
  
      }
  
@@ -289,7 +336,7 @@ diff -ur cvs-1.11.5.orig/src/logmsg.c cvs-1.11.5/src/logmsg.c
      if (*messagep)
 diff -ur cvs-1.11.5.orig/src/sanity.sh cvs-1.11.5/src/sanity.sh
 --- cvs-1.11.5.orig/src/sanity.sh	Thu Dec 19 15:38:32 2002
-+++ cvs-1.11.5/src/sanity.sh	Tue Apr 22 15:00:47 2003
++++ cvs-1.11.5/src/sanity.sh	Sun Apr 27 13:25:26 2003
 @@ -176,8 +176,8 @@
  #     So this would be lost if everything was `pwd`-based.  I suppose
  #     if we wanted to get baroque we could start making symlinks
@@ -301,60 +348,61 @@ diff -ur cvs-1.11.5.orig/src/sanity.sh cvs-1.11.5/src/sanity.sh
  
  # Now:
  #	1) Set TESTDIR if it's not set already
-@@ -185,17 +185,23 @@
+@@ -185,25 +185,31 @@
  #	3) Create $TESTDIR
  #	4) Normalize TESTDIR with `cd && (/bin/pwd || pwd)`
  #	   (This will match CVS output later)
 -: ${TESTDIR=$tmp/cvs-sanity}
--# clean any old remnants (we need the chmod because some tests make
--# directories read-only)
++if [ -n "$TESTDIR" ]; then
+ # clean any old remnants (we need the chmod because some tests make
+ # directories read-only)
 -if test -d ${TESTDIR}; then
 -    chmod -R a+wx ${TESTDIR}
 -    rm -rf ${TESTDIR}
 -fi
--# These exits are important.  The first time I tried this, if the `mkdir && cd`
--# failed then the build directory would get blown away.  Some people probably
--# wouldn't appreciate that.
++  if test -d $TESTDIR; then
++    chmod -R u+wx $TESTDIR
++    rm -rf -- $TESTDIR
++  fi
+ # These exits are important.  The first time I tried this, if the `mkdir && cd`
+ # failed then the build directory would get blown away.  Some people probably
+ # wouldn't appreciate that.
 -mkdir ${TESTDIR} || exit 1
-+if [ -n "$TESTDIR" ]; then
-+	# clean any old remnants (we need the chmod because some tests make
-+	# directories read-only)
-+	if test -d ${TESTDIR}; then
-+	    chmod -R u+wx ${TESTDIR}
-+	    rm -rf ${TESTDIR}
-+	fi
-+	# These exits are important.  The first time I tried this, if the `mkdir && cd`
-+	# failed then the build directory would get blown away.  Some people probably
-+	# wouldn't appreciate that.
-+	mkdir ${TESTDIR} || exit 1
+-cd ${TESTDIR} || exit 1
+-TESTDIR=`(/bin/pwd || pwd) 2>/dev/null`
++  mkdir $TESTDIR || exit 1
++  cd $TESTDIR || exit 1
++  TESTDIR=`(/bin/pwd || pwd) 2>/dev/null`
 +else
-+	TESTDIR=
-+	trap 'rm -rf -- "$TESTDIR"' EXIT
-+	trap 'trap - EXIT ; rm -rf -- "$TESTDIR"; exit 1' HUP INT QUIT TERM
-+	TESTDIR=`/bin/mktemp -td cvs-sanity.XXXXXXXXXX` || exit
++  TESTDIR=
++  trap 'cd "$TESTDIR/.."; rm -rf -- "$TESTDIR"' EXIT
++  trap 'trap - EXIT; cd "$TESTDIR/.."; rm -rf -- "$TESTDIR"; exit 1' HUP INT QUIT TERM
++  TESTDIR="`mktemp -td cvs-sanity.XXXXXXXXXX`" || exit
 +fi
- cd ${TESTDIR} || exit 1
- TESTDIR=`(/bin/pwd || pwd) 2>/dev/null`
  # Ensure $TESTDIR is absolute
-@@ -732,14 +738,22 @@
+-if test -z "${TESTDIR}" || echo "${TESTDIR}" |grep '^[^/]'; then
++if test -z "$TESTDIR" || echo "$TESTDIR" |grep '^[^/]'; then
+     echo "Unable to resolve TESTDIR to an absolute directory." >&2
+     exit 1
+ fi
+-cd ${TESTDIR}
++cd $TESTDIR || exit 1
+ 
+ # Make sure various tools work the way we expect, or try to find
+ # versions that do.
+@@ -732,14 +738,16 @@
  	DIR_2=$2
  
  	cd $DIR_1
 -	find . -print | fgrep -v /CVS | sort > /tmp/dc$$d1
-+	dcd1=
-+	trap 'rm -rf -- "$dcd1"' EXIT
-+	trap 'trap - EXIT ; rm -rf -- "$dcd1"; exit 1' HUP INT QUIT TERM
-+	dcd1=`mktemp -t dcd1.XXXXXXXXXX`
++	dcd1="$TESTDIR/dcd1"
 +	find . -print | fgrep -v /CVS | sort > "$dcd1"
  
  	# go back where we were to avoid symlink hell...
  	cd $OLDPWD
  	cd $DIR_2
 -	find . -print | fgrep -v /CVS | sort > /tmp/dc$$d2
-+        dcd2=
-+        trap 'rm -rf -- "$dcd2"' EXIT
-+        trap 'trap - EXIT ; rm -rf -- "$dcd2"; exit 1' HUP INT QUIT TERM
-+        dcd1=`mktemp -t dcd2.XXXXXXXXXX`
++        dcd2="$TESTDIR/dcd2"
 +	find . -print | fgrep -v /CVS | sort > "$dcd2"
  
 -	if diff /tmp/dc$$d1 /tmp/dc$$d2 >/dev/null 2>&1
@@ -362,7 +410,7 @@ diff -ur cvs-1.11.5.orig/src/sanity.sh cvs-1.11.5/src/sanity.sh
  	then
  		:
  	else
-@@ -754,8 +768,8 @@
+@@ -754,8 +762,8 @@
  				return 1
  			fi
  		fi
@@ -373,3 +421,13 @@ diff -ur cvs-1.11.5.orig/src/sanity.sh cvs-1.11.5/src/sanity.sh
  	return 0
  }
  
+@@ -24057,7 +24065,7 @@
+ fi
+ 
+ # Remove the test directory, but first change out of it.
+-cd `dirname ${TESTDIR}`
+-rm -rf ${TESTDIR}
++cd "$TESTDIR/.."
++rm -rf $TESTDIR
+ 
+ # end of sanity.sh
