Use tabs for indentation.
Don't use explicit paths for commands (other than with "test") because
we set PATH anyway.

CVS-ID: packages/kbd/setsysfont 1.2

diff --git a/packages/kbd/setsysfont b/packages/kbd/setsysfont
--- a/packages/kbd/setsysfont
+++ b/packages/kbd/setsysfont
@@ -3,30 +3,29 @@
 PATH=/bin:/usr/bin
 
 if [ -f /etc/sysconfig/i18n ]; then
-  . /etc/sysconfig/i18n
+	. /etc/sysconfig/i18n
 fi
 
 if [ -x /bin/consolechars -o -x /usr/bin/consolechars ]; then
-  if [ -n "$SYSFONT" ]; then
-    ARGS="$SYSFONT"
-    if [ -n "$UNIMAP" ]; then
-       ARGS="$ARGS --sfm $UNIMAP"
-    fi
-    if [ -n "$SYSFONTACM" ]; then
-       ARGS="$ARGS --acm $SYSFONTACM"
-    fi
-    consolechars -f $ARGS
-  fi
+	if [ -n "$SYSFONT" ]; then
+		ARGS="$SYSFONT"
+		if [ -n "$UNIMAP" ]; then
+			ARGS="$ARGS --sfm $UNIMAP"
+		fi
+		if [ -n "$SYSFONTACM" ]; then
+			ARGS="$ARGS --acm $SYSFONTACM"
+		fi
+		consolechars -f $ARGS
+	fi
 elif [ -x /bin/setfont ]; then
-  if [ -n "$SYSFONT" -a -n "$UNIMAP" ]; then
-    /bin/setfont "$SYSFONT" -u "$UNIMAP"
-  elif [ -n "$SYSFONT" ]; then
-    /bin/setfont "$SYSFONT"
-#  else
-#    /usr/bin/setfont
-  fi
+	if [ -n "$SYSFONT" -a -n "$UNIMAP" ]; then
+		setfont "$SYSFONT" -u "$UNIMAP"
+	elif [ -n "$SYSFONT" ]; then
+		setfont "$SYSFONT"
+	fi
 else
-  echo "can't set font"
-  exit 1
+	echo "Can't set font"
+	exit 1
 fi
+
 exit 0
