Further enhancements to the script inspired by its version in ALT Linux.
CVS-ID: packages/owl-startup/service 1.2

diff --git a/packages/owl-startup/service b/packages/owl-startup/service
--- a/packages/owl-startup/service
+++ b/packages/owl-startup/service
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Id: Owl/packages/owl-startup/service,v 1.1 2004/01/18 11:35:55 solar Exp $
+# $Id: Owl/packages/owl-startup/service,v 1.2 2004/01/18 12:31:15 solar Exp $
 
 # This script is mostly compatible with Red Hat's service script,
 # version 0.91.  However, it is not so ugly and support for option
@@ -10,15 +10,31 @@ SERVICEDIR=/etc/init.d
 
 function usage()
 {
-	echo -n "Usage: `basename $0` --version | " >&2
+	echo -n "Usage: ${0##*/} --version | " >&2
 	echo "[ service_name [ command | --full-restart ] ]" >&2
+	exit $1
+}
+
+function fatal()
+{
+	echo "${0##*/}: $*" >&2
+	exit 1
+}
+
+function check_service()
+{
+	if [ -z "${SERVICE##*/*}" ]; then
+		fatal "$SERVICE: Invalid service name"
+	fi
+	if [ ! -x "$SERVICEDIR/$SERVICE" ]; then
+		fatal "$SERVICE: Unrecognized service"
+	fi
 }
 
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
 
 if [ $# -eq 0 ]; then
-	usage
-	exit 1
+	usage 1
 fi
 
 SERVICE=
@@ -27,28 +43,26 @@ OPTIONS=
 while [ $# -gt 0 ]; do
 	case "$1" in
 	--help|-h)
-		usage
-		exit 0
+		usage 0
 		;;
 	--version|-V)
 		echo "$VERSION"
 		exit 0
 		;;
 	-*)
-		usage
-		exit 1
+		usage 1
 		;;
 	*)
 		if [ $# -eq 2 -a "$2" = "--full-restart" ]; then
 			SERVICE="$1"
-			if [ -x $SERVICEDIR/$SERVICE ]; then
-				cd / || exit
-				$SERVICEDIR/$SERVICE stop
-				$SERVICEDIR/$SERVICE start
-				exit $?
-			fi
+			check_service
+			cd / || exit
+			"$SERVICEDIR/$SERVICE" stop
+			"$SERVICEDIR/$SERVICE" start
+			exit $?
 		elif [ -z "$SERVICE" ]; then
 			SERVICE="$1"
+			check_service
 		else
 			OPTIONS="$OPTIONS $1"
 		fi
@@ -57,10 +71,5 @@ while [ $# -gt 0 ]; do
 	esac
 done
 
-if [ -x $SERVICEDIR/$SERVICE ]; then
-	cd / || exit
-	$SERVICEDIR/$SERVICE $OPTIONS
-else
-	echo "`basename $0`: $SERVICE: unrecognized service" >&2
-	exit 1
-fi
+cd / || exit
+"$SERVICEDIR/$SERVICE" $OPTIONS
