- Changed zgrep, zdiff and zmore utilities to handle also functionality of bz*grep, bzdiff and bzmore utilities, packaged bz*grep, bzcmp, bzdiff, bzmore and bzless within this package.
CVS-ID: packages/gzip/gzip-1.3.5-alt-bzip2.diff 1.1
CVS-ID: packages/gzip/gzip-1.3.5-rh-alt-stderr.diff 1.2
CVS-ID: packages/gzip/gzip-1.3.5-rh-owl-alt-zgrep.diff 1.2
CVS-ID: packages/gzip/gzip.spec 1.16

diff --git a/packages/gzip/gzip-1.3.5-rh-alt-stderr.diff b/packages/gzip/gzip-1.3.5-rh-alt-stderr.diff
--- a/packages/gzip/gzip-1.3.5-rh-alt-stderr.diff
+++ b/packages/gzip/gzip-1.3.5-rh-alt-stderr.diff
@@ -1,6 +1,6 @@
 diff -upk.orig gzip-1.3.5.orig/gzexe.in gzip-1.3.5/gzexe.in
---- gzip-1.3.5.orig/gzexe.in	2005-05-19 14:04:03 +0000
-+++ gzip-1.3.5/gzexe.in	2005-05-19 14:05:03 +0000
+--- gzip-1.3.5.orig/gzexe.in	2005-05-20 14:14:25 +0000
++++ gzip-1.3.5/gzexe.in	2005-05-20 14:14:43 +0000
 @@ -36,10 +36,10 @@
  PATH="BINDIR:$PATH"
  x="${0##*/}"
@@ -17,9 +17,16 @@ diff -upk.orig gzip-1.3.5.orig/gzexe.in gzip-1.3.5/gzexe.in
  
  decomp=0
 diff -upk.orig gzip-1.3.5.orig/zdiff.in gzip-1.3.5/zdiff.in
---- gzip-1.3.5.orig/zdiff.in	2005-05-19 14:04:03 +0000
-+++ gzip-1.3.5/zdiff.in	2005-05-19 14:04:17 +0000
-@@ -32,7 +32,7 @@ do
+--- gzip-1.3.5.orig/zdiff.in	2005-05-20 14:14:25 +0000
++++ gzip-1.3.5/zdiff.in	2005-05-20 14:15:02 +0000
+@@ -26,13 +26,13 @@ do
+      *)	if test -f "$ARG"; then
+             FILES="$FILES $ARG"
+         else
+-            echo "${prog}: $ARG not found or not a regular file"
++            echo "${prog}: $ARG not found or not a regular file" >&2
+ 	    exit 2
+         fi ;;
      esac
  done
  if test -z "$FILES"; then
@@ -37,8 +44,8 @@ diff -upk.orig gzip-1.3.5.orig/zdiff.in gzip-1.3.5/zdiff.in
  	exit 2
  fi
 diff -upk.orig gzip-1.3.5.orig/zforce.in gzip-1.3.5/zforce.in
---- gzip-1.3.5.orig/zforce.in	2005-05-19 14:04:03 +0000
-+++ gzip-1.3.5/zforce.in	2005-05-19 14:06:07 +0000
+--- gzip-1.3.5.orig/zforce.in	2005-05-20 14:14:25 +0000
++++ gzip-1.3.5/zforce.in	2005-05-20 14:14:43 +0000
 @@ -29,9 +29,9 @@
  PATH="BINDIR:$PATH"; export PATH
  x="${0##*/}"
@@ -53,8 +60,8 @@ diff -upk.orig gzip-1.3.5.orig/zforce.in gzip-1.3.5/zforce.in
  
  res=0
 diff -upk.orig gzip-1.3.5.orig/zgrep.in gzip-1.3.5/zgrep.in
---- gzip-1.3.5.orig/zgrep.in	2005-05-19 14:04:03 +0000
-+++ gzip-1.3.5/zgrep.in	2005-05-19 14:04:17 +0000
+--- gzip-1.3.5.orig/zgrep.in	2005-05-20 14:14:25 +0000
++++ gzip-1.3.5/zgrep.in	2005-05-20 14:14:43 +0000
 @@ -81,8 +81,8 @@ while test $# -ne 0; do
  done
  
@@ -67,8 +74,8 @@ diff -upk.orig gzip-1.3.5.orig/zgrep.in gzip-1.3.5/zgrep.in
  fi
  
 diff -upk.orig gzip-1.3.5.orig/zmore.in gzip-1.3.5/zmore.in
---- gzip-1.3.5.orig/zmore.in	2005-05-19 14:04:03 +0000
-+++ gzip-1.3.5/zmore.in	2005-05-19 14:06:00 +0000
+--- gzip-1.3.5.orig/zmore.in	2005-05-20 14:14:25 +0000
++++ gzip-1.3.5/zmore.in	2005-05-20 14:14:43 +0000
 @@ -41,7 +41,8 @@ fi
  
  if test $# = 0; then
@@ -80,8 +87,8 @@ diff -upk.orig gzip-1.3.5.orig/zmore.in gzip-1.3.5/zmore.in
  	gzip -cdfq | eval ${PAGER-more}
      fi
 diff -upk.orig gzip-1.3.5.orig/znew.in gzip-1.3.5/znew.in
---- gzip-1.3.5.orig/znew.in	2005-05-19 14:04:03 +0000
-+++ gzip-1.3.5/znew.in	2005-05-19 14:05:54 +0000
+--- gzip-1.3.5.orig/znew.in	2005-05-20 14:14:25 +0000
++++ gzip-1.3.5/znew.in	2005-05-20 14:14:43 +0000
 @@ -51,14 +51,14 @@ do
  done
  
