Various important changes to the provided shell functions.
CVS-ID: packages/owl-control/control 1.2
CVS-ID: packages/owl-control/functions 1.2

diff --git a/packages/owl-control/functions b/packages/owl-control/functions
--- a/packages/owl-control/functions
+++ b/packages/owl-control/functions
@@ -1,58 +1,119 @@
-# $Id: Owl/packages/owl-control/functions,v 1.1 2000/08/10 07:33:15 solar Exp $
+# $Id: Owl/packages/owl-control/functions,v 1.2 2000/08/11 03:53:54 solar Exp $
 
 function define()
 {
-	eval "$1_$2=$3"
+	eval "$1_$2='$3'"
 }
 
 function lookup()
 {
-	echo "$2" | grep '^[a-z0-9-]*$' &> /dev/null && eval "echo \$$1_$2"
+	eval "echo \$$1_$2"
 }
 
-function mode()
+function validate()
 {
-	test -z "$NAME_LIST" && NAME_LIST=$1 || NAME_LIST="$NAME_LIST $1"
-	define NAME_TO_MODE "$1" "$2"
+	echo "$1" | grep '^[a-z0-9_]*$' > /dev/null
+}
+
+function register()
+{
+	test -z "`lookup REGISTERED "$1"`" || return
+	define REGISTERED "$1" yes
+	test -z "$NAME_LIST" && NAME_LIST="$1" || NAME_LIST="$NAME_LIST $1"
+}
+
+function new_fmode()
+{
+	register "$1"
+	define NAME_TO_FMODE "$1" "$2"
 	define NAME_TO_OWNER "$1" "$3.$4"
-	define MODE_TO_NAME "$2" "$1"
+	define FMODE_OWNER_TO_NAME "$2_$3_$4" "$1"
+}
+
+function new_subst()
+{
+	register "$1"
+	define NAME_TO_REGEX "$1" "$2"
+	define NAME_TO_SUBST "$1" "$3"
 }
 
 function stat()
 {
-	local BASEDIR STAT
+	local PATHNAME="$1"
+	local BASEPATH
 
-	BASEDIR="`echo $1 | sed 's,/[^/]*$,,'`"
-	STAT="`find "$BASEDIR" -path "$1" -maxdepth 1 -printf '%m %u.%g'`"
-	ST_MODE=`echo "$STAT" | sed 's/^\([^ ]*\) .*$/\1/'`
-	ST_OWNER=`echo "$STAT" | sed 's/^[^ ]* \(.*\)$/\1/'`
+	BASEPATH="`echo "$PATHNAME" | sed 's,/[^/]*$,,'`"
+	find "$BASEPATH" -path "$PATHNAME" -maxdepth 1 -printf '%m_%u_%g'
 }
 
-function control_mode()
+function control_fmode()
 {
-	case "$1" in
+	local FILE="$1" REQUEST="$2"
+	local STAT NAME FMODE OWNER
+
+	case "$REQUEST" in
 	list)
 		echo "$NAME_LIST"
 		;;
 	status|'')
-		stat $CONTROL_FILE
-		NAME=`lookup MODE_TO_NAME "$ST_MODE"`
-		OWNER=`lookup NAME_TO_OWNER "$NAME"`
-		if [ -n "$NAME" -a "$ST_OWNER" = "$OWNER" ]; then
+		STAT="`stat "$FILE"`"
+		NAME="`validate "$STAT" && lookup FMODE_OWNER_TO_NAME "$STAT"`"
+		if [ -n "$NAME" ]; then
 			echo "$NAME"
 		else
 			echo "unknown"
 		fi
 		;;
 	*)
-		MODE=`lookup NAME_TO_MODE $1`
-		OWNER=`lookup NAME_TO_OWNER $1`
-		if [ -n "$MODE" -a -n "$OWNER" ]; then
-			chown $OWNER $CONTROL_FILE || exit 1
-			chmod $MODE $CONTROL_FILE || exit 1
+		FMODE="`validate "$REQUEST" && lookup NAME_TO_FMODE "$REQUEST"`"
+		OWNER="`validate "$REQUEST" && lookup NAME_TO_OWNER "$REQUEST"`"
+		if [ -n "$FMODE" -a -n "$OWNER" ]; then
+			chown "$OWNER" "$FILE" || return 1
+			chmod "$FMODE" "$FILE" || return 1
 		else
-			echo "$0: Invalid mode: $1"
+			echo "$0: Invalid mode: $REQUEST" >&2
+			return 1
 		fi
+		;;
+	esac
+}
+
+function control_subst()
+{
+	local FILE="$1" REQUEST="$2"
+	local NAME REGEX SUBST TMPFILE
+
+	case "$REQUEST" in
+	list)
+		echo "$NAME_LIST"
+		;;
+	status|'')
+		for NAME in $NAME_LIST; do
+			REGEX="`lookup NAME_TO_REGEX "$NAME"`"
+			test -n "$REGEX" || continue
+			if grep "$REGEX" "$FILE" > /dev/null; then
+				echo "$NAME"
+				return
+			fi
+		done
+		echo "unknown"
+		;;
+	*)
+		SUBST="`validate "$REQUEST" && lookup NAME_TO_SUBST "$REQUEST"`"
+		if [ -z "$SUBST" ]; then
+			echo "$0: Invalid mode: $REQUEST" >&2
+			return 1
+		fi
+		TMPFILE="`mktemp "$FILE.control.XXXXXX"`" || return 1
+		while :; do
+			cp -p "$FILE" "$TMPFILE" || break
+			sed "$SUBST" < "$FILE" > "$TMPFILE" || break
+			ln -f "$FILE" "$FILE.control.orig" || break
+			mv -f "$TMPFILE" "$FILE" || break
+			return
+		done
+		rm "$TMPFILE"
+		return 1
 		;;
 	esac
 }
