Updated to 1.0.5
CVS-ID: packages/bzip2/bzip2-1.0.4-alt-autotools.diff 1.1.2.2
CVS-ID: packages/bzip2/bzip2-1.0.4-alt-const.diff 1.1.2.2
CVS-ID: packages/bzip2/bzip2-1.0.4-alt-owl-fopen.diff 1.3.2.2
CVS-ID: packages/bzip2/bzip2-1.0.4-alt-owl-versioning.diff 1.1.2.2
CVS-ID: packages/bzip2/bzip2-1.0.4-alt-progname.diff 1.1.2.2
CVS-ID: packages/bzip2/bzip2-1.0.4-owl-Makefile.diff 1.1.2.2
CVS-ID: packages/bzip2/bzip2-1.0.4-owl-bzdiff-tmp.diff 1.1.2.2
CVS-ID: packages/bzip2/bzip2.spec 1.26.2.1
CVS-ID: packages/bzip2/bzip2.texi 1.3.2.1

diff --git a/packages/bzip2/bzip2-1.0.4-owl-bzdiff-tmp.diff b/packages/bzip2/bzip2-1.0.4-owl-bzdiff-tmp.diff
--- a/packages/bzip2/bzip2-1.0.4-owl-bzdiff-tmp.diff
+++ b/packages/bzip2/bzip2-1.0.4-owl-bzdiff-tmp.diff
@@ -1,22 +1,36 @@
-diff -ur bzip2-1.0.3.orig/bzdiff bzip2-1.0.3/bzdiff
---- bzip2-1.0.3.orig/bzdiff	Sat Oct  9 11:29:42 2004
-+++ bzip2-1.0.3/bzdiff	Thu May  5 22:07:47 2005
-@@ -37,10 +37,6 @@
+--- bzip2-1.0.4/bzdiff.orig	2007-01-10 16:00:19 +0000
++++ bzip2-1.0.4/bzdiff	2007-01-10 16:09:48 +0000
+@@ -12,7 +12,10 @@
+ # necessary) and fed to cmp or diff.  The exit status from cmp
+ # or diff is preserved.
+ 
+-PATH="/usr/bin:/bin:$PATH"; export PATH
++[ -z "$PATH" ] &&
++	PATH="/bin:/usr/bin" ||
++	PATH="/bin:/usr/bin:$PATH"
++export PATH
+ prog=`echo $0 | sed 's|.*/||'`
+ case "$prog" in
+   *cmp) comp=${CMP-cmp}   ;;
+@@ -37,10 +40,6 @@ if test -z "$FILES"; then
  	echo "Usage: $prog [${comp}_options] file [file]"
  	exit 1
  fi
--tmp=`tempfile -d /tmp -p bz` || {
+-tmp=`mktemp ${TMPDIR:-/tmp}/bzdiff.XXXXXXXXXX` || {
 -      echo 'cannot create a temporary file' >&2
 -      exit 1
 -}
  set $FILES
  if test $# -eq 1; then
  	FILE=`echo "$1" | sed 's/.bz2$//'`
-@@ -52,11 +48,13 @@
+@@ -52,11 +51,16 @@ elif test $# -eq 2; then
          *.bz2)
                  case "$2" in
  	        *.bz2)
-+			tmp="`mktemp -t bzdiff.XXXXXXXXXX`" || exit
++			tmp="`mktemp -t bzdiff.XXXXXXXXXX`" || {
++				echo 'cannot create a temporary file' >&2
++				exit 1
++			}
 +			trap 'rm -f -- "$tmp"' EXIT
 +			trap 'trap - EXIT; rm -f -- "$tmp"; exit 1' HUP INT QUIT PIPE TERM
  			F=`echo "$2" | sed 's|.*/||;s|.bz2$||'`
